### ISSUE TITLE
ADO bug filing should handle needing to refresh bugs

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#1003]
In one of the internal jobs, we saw the error "TF26071: This work item has been changed by someone else since you opened it.  You will need to refresh it and discard your changes.".

We should catch this error, refresh the work item, and resubmit the change. 

AB#39994479

**Comment by chkeita** [comment]
This issue still occurs after the fix

```
job: 23211076-bf75-4fac-aea4-d2b7abedafdc
project:tcpip name:s1 build:stable
tasks:
0b1a3268 target:tcpip.exe state:stopped type:generic_supervisor
14df0356 target:tcpip.exe state:stopped type:generic_analysis
tasks with errors:
d726f486 type:generic_analysis target:tcpip.exe
error:
notification failed
TF26071: This work item has been changed by someone else since you opened it.  You will need to refresh it and discard your changes.
```

**Comment by chkeita** [comment]
need to add job id and task id to the error logged in appinsight on transient error

**Comment by tevoinea** [comment]
While we don't explicitly handle this error, #2555 added an exponential backoff to our notification reprocessing. This gives us 5 chances to make the modification to the work item over varying time periods so it's unlikely that a notification will fail to be created 5 times in a row due to this error.

Closing for now, we can reopen if we see this becoming an issue in the future.
