### ISSUE TITLE
MS Teams Notification - Issue - Incomplete Alert metadata

### ISSUE THREAD

**Issue by rthenmozhis** [microsoft/onefuzz#1260]
## Information

- Onefuzz version: onefuzz-2.33.1
- OS: Ubuntu 20.04

## Provide detailed reproduction steps (if any)

1. Created a notification with a incoming webhook for unique crash reports
2. Got successful alerts to the MS team channel 
3. But issue with alert information :  incomplete and blanked out data on the alert

### Expected result

 Call Stack shown with all metadata 

### Actual result

Incomplete Alert ( Please find attached Screeshot)
![image](https://user-images.githubusercontent.com/82480246/134265345-2612d95c-2c7c-4e94-83b3-3ef35aca1ad0.png)

**Comment by puhley** [comment]
I have identified the root cause of this issue. The bug exists in the file:

`https://github.com/microsoft/onefuzz/blob/main/src/api-service/__app__/onefuzzlib/notifications/teams.py`

Within the _code_block_ function, line 29 attempts to return strings representing a Markdown code block:

````
return "\n```%s\n```\n" % data
````

The problem is that there needs to be a newline ("\n") before the "%s". Assuming that "%s" represents the _data_ string "foo", the existing code will generate the following two lines (with the newlines interpreted):

````
```foo
```
````

This is not a valid Markdown code block. The same behavior seen in the Teams screenshot above can be reproduced in GitHub's Markdown.  For instance, I will add those lines below:

```foo
```

In order to be rendered correctly in Markdown, the data needs to be on a separate line from the backticks. Therefore, the function should be returning the following lines (with the newlines interpreted):
````
```
foo
```
```` 

I can create a pull request with the extra newline inserted before the "%s" to separate the backticks from the data.
