### ISSUE TITLE
add windows-latest example for github-pipeline.yml

### ISSUE THREAD

**Issue by dthaler** [microsoft/onefuzz#1305]
https://github.com/microsoft/onefuzz/blob/main/contrib/onefuzz-job-github-actions/github-pipeline.yml
only has "runs-on: ubuntu-latest". Can we get a sample for windows-latest?

**Comment by ranweiler** [comment]
Hi @dthaler! Generally, we do want to provide helpful examples for Windows-specific flows.

In this case, the Windows version would be nearly identical to the linked Linux example. This is because almost all of the invoked commands are cross-platform. The only difference is that the `run` script should probably use PowerShell instead of `sed`. Even that might work as-is on `windows-latest`, if you set `shell: bash`, depending on what is installed in the GitHub Actions environment.

I don't know how familiar you are with OneFuzz yet, but just to emphasize: the OS used to deploy a job in a pipeline doesn't have anything to do with the OS that the job runs on. That is determined by the OS type of the `pool`. In the linked example, although the `ONEFUZZ_POOL` variable is `linux`, which actually describes the _name_ of some pool that is assumed to exist. All that said, I can understand that a team may want to standardize on one VM type for their CI actions!

Rather than maintain very slight variants of actions for both OS types in our repo, I think it'd be most useful to add documenting comments to the existing example. We'd accept a PR for a Windows action, though, especially if it demonstrated a common Windows-specific workflow.

**Comment by ranweiler** [comment]
@dthaler, please let us know if the additions in #1309 seem sufficient to bridging the gap, or if there's anything that is still unclear.
