### ISSUE TITLE
Add task setup container path as an environment variable when launching setup scripts

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#14]
It would be useful to know the path to the setup container in the setup scripts.  While this can be calculated via `BASEDIR=$(dirname $0)` in bash or `PSScriptRoot` for powershell, passing it as an environment variable would be helpful.

Perhaps use `ONEFUZZ_TASK_SETUP_PATH`

**Comment by ranweiler** [comment]
I suggest `$ONEFUZZ_TASK_DIR` and maybe `$ONEFUZZ_TASK_ID`, too. We'd like the setup container to be conveniently accessible too, but it ultimately inherits its dynamic path from the dynamic `$ONEFUZZ_TASK_DIR`.

**Comment by ranweiler** [comment]
Oops, self-correction: task ID is not in general uniquely defined at setup runtime, `$ONEFUZZ_TASK_DIR` / `$ONEFUZZ_TASK_ID` are not defined as setup script env vars. 

The setup container for a work set _is_ defined, because we assume and require that the tasks within a work set share a common setup dir, whose script must be run exactly once. It should be set to `$ONEFUZZ_ROOT/blob-containers/<setup-container>`.
