### ISSUE TITLE
Task failing to start after another independent task failed for same job

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#1509]
## Information

- Onefuzz version: 3.2.0
- OS: Windows

## Provide detailed reproduction steps (if any)

Started a job with 3 tasks:

1. A `generic_supervisor` task: `S1`
2. A `generic_supervisor` task: `S2`
3. A `generic_analysis` task: `A1`

* `A1` has a prereq on `S1`
* `S1` and `S2` have no prereqs
* `S1` failed due to a bug in the target exe (unrelated to OneFuzz)

### Expected result

`S2` to start

### Actual result

The job appears to have stopped and an error stating `S2` never started. Example job id where this occurred: `ffe5b2aa-f559-40c3-8110-55148f126965`.

**Comment by chkeita** [comment]
I can't repro the issue. 
Here is my test setup which is based on the radamsa template:
- G1: generator task which fails because of a bad parameter
- G2: normal generator task 
- C1: crash report task that depends on G1  


here is a screenshot of the state of the task. As expected, the crash report task C1 is stopping because its prerequisite (G1) failed. But the second generator task (G2) is running
![image](https://user-images.githubusercontent.com/244326/147980423-ad576cfc-5574-43a0-af25-5d4fd2c062b4.png)

**Comment by jagunter** [comment]
Yeah it doesn't repro 100% of the time. Can you see what happened in the job provided?

**Comment by chkeita** [comment]
the logs for this job are no longer available. Closing this for now.
