### ISSUE TITLE
replace memmap crate

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#363]
As identified by `cargo audit` in our [CICD](https://github.com/microsoft/onefuzz/runs/1488395856?check_suite_focus=true), the memmap crate is apparently abandoned.  We should investigate replacing it with a maintained alternative.

Reference: https://github.com/RustSec/advisory-db/issues/359

**Comment by bmc-msft** [comment]
We use `memmap` in the `coverage` and `debugger` crates.  @ranweiler or @lzybkr, since you are active in this code, can one of you investigate this?

**Comment by ranweiler** [comment]
@bmc-msft, yes. Per this [discussion](https://github.com/RustSec/advisory-db/issues/359), the [`mapr`](https://crates.io/crates/mapr) crate may be a reasonable alternative. Will poke around.

**Comment by ranweiler** [comment]
At first glance: I think it would be better to push towards getting `memmap` itself maintained again (which is something I'd be interested in helping with). The crate itself is relatively small. `mapr` seems to be primarily forked so that user could land a PR for their project. The primary author of `memmap` has recent nontrivial GH activity. Will poke around forums.

**Comment by ranweiler** [comment]
I left a [comment](https://github.com/danburkert/memmap-rs/issues/90#issuecomment-737476499) in the repo, volunteering to help maintain, and pinging the latest active co-maintainer, who at least has repo activity in 2020.

**Comment by ranweiler** [comment]
No response from the `memmap` maintainer; based on discussion, I think we should switch to `memmap2-rs`.
