### ISSUE TITLE
Install the Visual c++ 2015 Redistributable in all VMs in the Github Repo

### ISSUE THREAD

**Issue by milamarty** [microsoft/onefuzz#556]
Feature request is to install the Visual c++ 2015 Redistributable in all VMs in the Github Repo.

ASAN has a dependency on the C++ 2015 redist. That means if you run a binary built with ASAN it will look for specific binaries from that redist. Since this impacts every user that uses ASAN it makes more sense to have this done at an instance or github repo level instead of a per-job level.

The reason jobs work today is that OneFuzz fuzzing tasks are ran inside a debugger which has access to those binaries so they work. If you RDP to a VM and try and run a fuzzer from the CMD it will fail to find the required binaries. Adding this to all VMs will improve the user debugging experience if they ever need to RDP into VM along with reducing the number of binaries that need to be shipped with every job.

**Comment by bmc-msft** [comment]
This should work like `Install-LLVM`:

https://github.com/microsoft/onefuzz/blob/e2e44ace8a722d70dfe09fb45c9908d10ef15394/src/runtime-tools/win64/onefuzz.ps1#L114-L122

**Comment by anslutsk** [comment]
Should we install the x86 or x64 version of the redistributable and where should we get the installer? I used the web portal to get a URI but I'm concerned it could change and we don't want the setup script to fail just because the redistributable URI is not accessible, right?

From: https://www.microsoft.com/en-us/download/details.aspx?id=52685

Got the x64 version URI: https://www.microsoft.com/en-us/download/confirmation.aspx?id=52685&6B49FDFB-8E5B-4B07-BC31-15695C5A2143

Thoughts?

**Comment by bmc-msft** [comment]
Probably both.

Note, choco installs these via a more stable URLs, seen [here](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/vcredist2017/update.ps1) and [here](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/vcredist140/update.ps1)

**Comment by milamarty** [comment]
This has now been completed.
