### ISSUE TITLE
Support updating existing notifications

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#840]
Right now, notification integrations can't be updated.  Only a new one created, and deleting the old one.

This makes updating tedious.  Instead, we should support updating existing notifications and make use of this in the templates. 

AB#35985

**Comment by jagunter** [comment]
Will `JobHelper.setup_notifications` use this update mechanism, or perhaps expose a flag to use it? We're using that helper currently but suspect could have the same issue with multiple notification configs since it [creates a notification](https://github.com/microsoft/onefuzz/blob/2aea006c509ca4a894cb452d740833e5d89e45f9/src/cli/onefuzz/templates/__init__.py#L168).

**Comment by bmc-msft** [comment]
I imagine setup_notifications will make use of the functionality.

**Comment by samueleresca** [comment]
@bmc-msft, is this issue available for pick it up?

**Comment by mgreisen** [comment]
We now have a `--replaceExisting` flag on  `notification create. `
