### ISSUE TITLE
Create a job from a previous job using OneFuzz CLI

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#958]
It would be nice if there was a way to easily rerun a job from the CLI. This could be useful in a couple of scenarios:

1. Extending a fuzzing run. If ran a fuzzer for 1 week and then want to run it for an additional week, it would be nice to be able to run the fuzzer again without needing to specify the exact arguments.
2. Fixing a fuzzer bug. If a fuzzing task fails due to an error in the fuzzer (not a crash in the target), it could be useful to rerun it after updating the fuzzer in the container.
3. Reproducing a bug. If a fuzzing task fails, it could be useful to rerun in some scenarios, e.g. testing after a OneFuzz upgrade.

**Comment by ranweiler** [comment]
I like the idea of making this as easy as possible. It is natural to want to "run this job again, but with just one thing changed". I think we need to tease apart the different use cases and compare them to the existing data model.

> 1. Extending a fuzzing run. If ran a fuzzer for 1 week and then want to run it for an additional week, it would be nice to be able to run the fuzzer again without needing to specify the exact arguments.

This should definitely be easy. There is stuff to think about with container existence and identity, but it seems reasonable to have something that fails fast if any dependent resource arguments (storage containers, pools) changed or are missing. We could solve this by both (1) always allowing argument _overrides_, and (2) having a notion of "invalidated" arguments that _must_ be overridden (treated as missing, and thus must be re-specified) to re-run the job (which should get a new ID).

> 2. Fixing a fuzzer bug. If a fuzzing task fails due to an error in the fuzzer (not a crash in the target), it could be useful to rerun it after updating the fuzzer in the container.

Let's think about what happens if we create a job from a template. Our setup container will be named `oft-setup-$x`, where `$x = hash(project, name, build, platform)`. If we change the actual fuzzer code, we should definitely change `build`, which implies the name of the container should change (at least in a template-based setting). This again could be solved by the argument invalidation idea, but now there is _dependency_: if you invalidate `build`, then the `setup` container should be invalidated, and should be re-specified. A complication: containers are really per-task, and in the general (non-template-based) case of job creation, there could be several `setup` containers. Should we only support re-running for template-based jobs?

> 3. Reproducing a bug. <...>

Agreed, like (1), this should be easy.

Right now, we don't explicitly track identifiable "job _runs_" as a datum. I think our data model tacitly _intends_ for a job ID to correspond to a run, though without any particular enforcement of this. Any "re-run" impl should either add a `run_id` to let us track identical re-runs of the exact same job/task parameters, or create new job/task IDs, even when the last run was identical.

**Comment by jagunter** [comment]
Overrides would absolutely be welcome, but I'm leery about anything that *needs* to be re-specified. For (2) the intent is more in line with a quick edit to correct a mistake, which OneFuzz already supports. Requiring new containers is contrary to this request, which is running a job with the same configuration as another job as simply as possible.

Agreed that OneFuzz is not currently architected to track "runs," and if (1) is repeated often enough that could be a useful addition. However I'm imagining this feature will be primarily beneficial in the testing/debugging loop of an initial deployment onto OneFuzz. I expect automation would submit jobs like today, which wouldn't take advantage of a `run_id`.

**Comment by ranweiler** [comment]
> leery about anything that _needs_ to be re-specified [...]

Totally. I'm just thinking through this as a potential mechanism to soften the failure mode if, on a re-run attempt, OneFuzz can't find a container that previously existed.

One use case that @bmc-msft brought up offline, where we'd probably really at least the constrained ability to override: "re-run this same job, but in `<other-region>`". Maybe we could literally only allow overriding a few specific, pre-chosen params, such as region?

> I'm imagining this feature will be primarily beneficial in the testing/debugging loop of an initial deployment [...]

Great, that's what I was thinking of as the core use case, too. Focusing on that lets us keep things simple.
